# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 20:39
from __future__ import unicode_literals

from django.db import migrations


def add_my_files(apps, schema_editor):
    SherlockBook = apps.get_model("app", "SherlockBook")

    with open("sample.txt") as open_holmes:
        holmes = open_holmes.read()
        SherlockBook.objects.create(text=holmes)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_my_files)
    ]
